[package]
name = "xc3_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.11.1"
flate2 = "1.0"
anyhow = "1.0"
tegra_swizzle = "0.3.1"
ddsfile = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bilge = "0.1.4"