[package]
name = "xc3_test"
version = "0.2.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
xc3_write = { path = "../xc3_write" }
clap = { version = "4.2.7", features = ["derive"] }
rayon = "1.7.0"
globwalk = "0.8.1"
binrw = "0.11.2"
