[package]
name = "xc3_model"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
xc3_shader = { path = "../xc3_shader" }
glam = { version = "0.23.0", features = ["bytemuck"] }
gltf = "1.2.0"
binrw = "0.11.2"
bytemuck = { version = "1.13", features = [ "derive" ] }
serde_json = "1.0"
image_dds = "0.1.1"
tegra_swizzle = "0.3.1"
ddsfile = "0.5.1"
rayon = "1.7.0"

[dev-dependencies]
hexlit = "0.5.5"