[package]
name = "xc3_model"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
glam = { version = "0.24.0", features = ["bytemuck"] }
gltf = { version = "1.3.0", features = ["extras"] }
binrw = "0.11.2"
image_dds = { git = "https://github.com/ScanMountGoat/image_dds", rev ="7aeea27" }
tegra_swizzle = "0.3.1"
ddsfile = "0.5.1"
rayon = "1.7.0"
image = "0.24.5"
log = "0.4.19"
ordered-float = "4.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "1.9.3", features = ["serde", "rayon"] }

[dev-dependencies]
hexlit = "0.5.5"