[package]
name = "xc3_model"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
glam = { version = "0.23.0", features = ["bytemuck"] }
gltf = "1.2.0"
binrw = "0.11.1"
bytemuck = { version = "1.13", features = [ "derive" ] }

[dev-dependencies]
hexlit = "0.5.5"