[package]
name = "xc3_model"
version = "0.3.0"
authors = ["ScanMountGoat <>"]
description = "High level library for xc3_lib"
license = "MIT"
documentation = "https://docs.rs/xc3_model"
repository = "https://github.com/ScanMountGoat/xc3_lib"
edition = "2021"

[dependencies]
xc3_lib = { version = "0.3.0", path = "../xc3_lib" }
glam = { version = "0.24.0", features = ["bytemuck"] }
gltf = { version = "=1.3.0", features = ["extras"] }
gltf-json = "=1.3.0"
binrw = "0.11.2"
image_dds = "0.4.0"
rayon = "1.7.0"
log = "0.4.19"
ordered-float = "4.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "1.9.3", features = ["serde", "rayon"] }
thiserror = "1.0"

[dev-dependencies]
hexlit = "0.5.5"
pretty_assertions = "1.4.0"
hex = "0.4.3"
