[package]
name = "xc3_model"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
xc3_shader = { path = "../xc3_shader" }
glam = { version = "0.24.0", features = ["bytemuck"] }
gltf = { version = "1.3.0", features = ["extras"] }
binrw = "0.11.2"
image_dds = { git = "https://github.com/ScanMountGoat/image_dds", rev ="d8848f3" }
tegra_swizzle = "0.3.1"
ddsfile = "0.5.1"
rayon = "1.7.0"
image = "0.24.5"
log = "0.4.19"

[dev-dependencies]
hexlit = "0.5.5"