[package]
name = "xc3_shader"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
rayon = "1.7.0"
globwalk = "0.8.1"
clap = { version = "4.2.7", features = ["derive"] }
glsl = "6.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "1.9.3", features = ["serde", "rayon"] }

[dev-dependencies]
indoc = "2"