[package]
name = "xc3_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.16.0"
xc3_lib = { path = "../xc3_lib" }
xc3_model = { path = "../xc3_model" }
xc3_shader = { path = "../xc3_shader" }
bytemuck = { version = "1.13", features = [ "derive" ] }
glam = { version = "0.23.0", features = ["bytemuck"] }
memoffset = "0.8.0"
futures-intrusive = "0.5.0"
rayon = "1.7.0"
binrw = "0.11.2"
serde_json = "1.0"
tegra_swizzle = "0.3.1" # TODO: avoid this dependency

[build-dependencies]
wgsl_to_wgpu = "0.4.1"