[package]
name = "xc3_wgpu"
version = "0.4.1"
authors = ["ScanMountGoat <>"]
description = "Xenoblade Chronicles model rendering library"
license = "MIT"
documentation = "https://docs.rs/xc3_wgpu"
repository = "https://github.com/ScanMountGoat/xc3_lib"
edition = "2021"

[dependencies]
wgpu = "0.18.0"
xc3_model = { version = "0.4.0", path = "../xc3_model" }
bytemuck = { version = "1.13", features = [ "derive" ] }
glam = { version = "0.24.0", features = ["bytemuck"] }
memoffset = "0.8.0"
rayon = "1.8.1"
log = "0.4.19"
tracing = "0.1.0"

[build-dependencies]
wgsl_to_wgpu = "0.5.0"
