[package]
name = "xc3_wgpu"
version = "0.7.0"
authors = ["ScanMountGoat <>"]
description = "Xenoblade Chronicles model rendering library"
license = "MIT"
documentation = "https://docs.rs/xc3_wgpu"
repository = "https://github.com/ScanMountGoat/xc3_lib"
edition = "2021"

[dependencies]
wgpu = "0.19.0"
xc3_model = { version = "0.7.0", path = "../xc3_model" }
xc3_lib = { version = "0.7.0", path = "../xc3_lib" }
bytemuck = { version = "1.13", features = [ "derive" ] }
glam = { version = "0.27.0", features = ["bytemuck"] }
encase = { git = "https://github.com/waywardmonkeys/encase", branch = "update-glam", features = ["glam"] }
rayon = "1.8.1"
log = "0.4.19"
tracing = "0.1.0"
indexmap = "2.1.0"

[build-dependencies]
wgsl_to_wgpu = { git = "https://github.com/ScanMountGoat/wgsl_to_wgpu", rev = "8bd2d22" }
