[package]
name = "xc3_tex"
version = "0.1.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
image_dds = "0.1.1"
ddsfile = "0.5.1"
clap = { version = "4.2.7", features = ["derive"] }